### ISSUE TITLE
Incorrect expectation/response when called concurrently under heavy load

### ISSUE THREAD

**Issue by fommil** [paulbutcher/ScalaMock#101] opened 2015-03-25 12:01 UTC
I have a Heisenbug and wondering what you think of this before considering making a minimal failing case.

I am passing a mock of an object into an actor, and about once in every 10,000 invocations, I see

```
25 Mar 15 11:30:47.944 akka.actor.OneForOneStrategy [ default-akka.actor.default-dispatcher-3] ERROR - null
java.lang.NullPointerException: null
    at org.scalamock.function.FakeFunction.handle(FakeFunction.scala:41) ~[org.scalamock-scalamock-core_2.11-3.2.1.jar:3.2.1]
    at org.scalamock.function.FakeFunction1.apply(FakeFunction.scala:57) ~[org.scalamock-scalamock-core_2.11-3.2.1.jar:3.2.1]
    at path.to.MySpec Spec$$anon$1.seqNoFor(MySpec.scala:246) ~[test-classes/:na]
```

and I'm wondering if a) is mocking supported across threads? b) is there a workaround? c) do you need a minimal failing case?

**Comment by paulbutcher** [comment] 2015-03-25 12:09
You definitely should be able to pass actors between threads. The code has certainly been written with this in mind, although multi-threading being what multi-threading is, it's quite possible that the synchronisation isn't what it should be.

Having said that, my guess from the failure mode you're seeing is that your actor is calling the mock after the test has completed (i.e. outside the scope of `withExpectations`). Is it possible that your test could be doing this?

If that doesn't turn out to be the problem, then a minimal failing case would be a huge help.

**Comment by fommil** [comment] 2015-03-25 13:10
oh, the timing issue might be happening. I'm getting a failing test and had assumed this was the cause. As great as actors are, they can be a real bugger to debug when it goes wrong.

**Comment by paulbutcher** [comment] 2015-03-25 13:30
That they can :-) I'll close this bug for now, but feel free to reopen if you discover something untoward.

**Comment by fommil** [comment] 2015-03-25 18:10
just confirmed that this is what you suspected. Definitely something I need to be aware of. Found the real culprit too.

**Comment by fommil** [comment] 2015-04-01 14:17
can we reopen this? I'm seeing transient failures in my work project that I am confident are coming from scalamock. I'd love to create you a minimal failing case but it's extremely difficult to get a repeatable failure. The general recipe is:

1. `MyTrait` which has a method `doStuff(): Unit`
2. `MyActor`, which takes a `MyTrait` as a parameter and calls `doStuff` (e.g. in `preStart`)
3. ScalaTest creating a `mock` with `OneInstancePerTest`. Setting the expectations before creating the actor, and then creating the Actor (testing via TestKit).

As is usual with actor testing, the failures usually manifest themselves as timeouts but looking in the logs one sees that the mocked method is throwing NPE.

I need to repeat my tests about 100 times, running about 5 - 10 in parallel, to see the dodgy behavior.

And, sods law, the more logging I add, the less probable the bug is to see!

**Comment by paulbutcher** [comment] 2015-04-01 15:57
Hmm, now that you've prompted me to look at this again, I'm becoming convinced that our synchronisation isn't right, which might be causing the problem that you're hitting.

I won't have time to spend on this for a while I'm afraid (I'm going to be racing over the weekend and then getting on a plane to the states to talk at a conference), but I might be able to give you a hint that will help you if you have time to look at it yourself.

Is the crash still at [line 41 of `FakeFunction.scala`](https://github.com/paulbutcher/ScalaMock/blob/master/core/src/main/scala/org/scalamock/function/FakeFunction.scala#L41)?

So, the problem seems to be that `callLog` is `null`? The only place that `callLog` is set to `null` is [within `clearExpectations` in `MockFactoryBase.scala`](https://github.com/paulbutcher/ScalaMock/blob/master/core/src/main/scala/org/scalamock/MockFactoryBase.scala#L84).

I think that the problem might be that `clearExpectations` isn't synchronised, meaning that the Java memory model doesn't guarantee memory consistency (the code in `MockFactoryBase` isn't synchronised either, but that's OK because it's only ever called from the `handle` or `verify` methods of either `OrderedHandlers` or `UnorderedHandlers`, and these methods are synchronised).

Certainly, now that I look at it, this code isn't correctly synchronised. But whether it's causing your problem or not, I don't know.

The more think about this, the more I come to the conclusion that we should globally synchronise on the mock context at each "entry point", rather than the current mix of synchronisation on `OrderedHandler`, `UnorderedHandler` and `CallLog`).

**Comment by fommil** [comment] 2015-04-01 16:19
Thanks! And good luck with the race :smile:

I still can't validate that scalamock is the problem 100%. This is manifesting itself as actors sending messages to themselves in `preStart` and the messages are hitting `deadLetters`. I have no exception logs or anything, which makes me think that only something funky with macros could be causing this.

I am planning on rewriting one of my tests to use an old-fashioned stub implementation, and if that makes the problem go away at least I can eliminate ScalaMock. I'll keep you posted.

**Comment by fommil** [comment] 2015-04-02 10:32
good news! It wasn't ScalaMock causing the tests to fail, it was a weird akka timing thing.

But at least this doubt has flagged up a potential (and even less likely) race condition somewhere else.

**Comment by davidB** [comment] 2015-07-06 12:21
Oups, I put my comments in wrong issue (10 days ago), so I move it.

Hi,

I use Testkit, but I have to add Thread.sleep(...) on some test to pass (on local). And The CI Server always failed when build is triggered by commit.

I have a combinaison of Actor (ask + pipeTo pattern) and Future.map(...) .
Code extracted from  my private project : 
```
class MovesSpec(system: ActorSystem) extends extends TestKit(system) with ImplicitSender with FlatSpecLike with ScalaFutures with MockFactory with OneInstancePerTest with BeforeAndAfterAll with BeforeAndAfterEach {
    def this() = this(ActorSystem("MySpec"))
//...
    val ioServiceMock = mock[IoService]

    "Auth" should "be simulated" in {
        ...
        (ioServiceMock.executeHttpReq _).expects(accessTokenRequest).
                returning(Future.successful(Response(HttpURLConnection.HTTP_OK, "application/x-www-form-urlencoded", readFile(".../response.json"))))
        (ioServiceMock.getCurrentTimestamp _).expects().returning(0L)
        (ioServiceMock.findAuthRedirect _).expects(cloudId).returning(oauthRedirectUrl).repeat(1)

        val config = ...
        val authService = new Oauth2Controller(ioServiceMock, config)
        authService.startAuthFlow(None)
        val res = authService.receivedAuthCodeAndGetToken("aDeviceId", RequestDef("endpoint", HttpMethod.Get, Map(("code", generatedCode), ("state", "astate")), contentType = "application/x-www-form-urlencoded"))
        assertResult(true, "Invalid result : " + res.futureValue)(res.futureValue.isGood)
        res.futureValue.get shouldEqual info0
    }
...
```
I have the same issue with mock declared inside the test block

Is it possible (as a workaround) to have a method that wait until actual every expected are satisfied or any unexpected call "actual" ?

I use  : 
* scalamock-scalatest-support_2.10:3.2.2
* scalatest_2.10:2.2.4
I run test from eclipse or maven.

Thanks!

**Comment by davidB** [comment] 2015-07-06 12:28
Today, I spent some time into a workaround, not perfect but better than Thread.sleep(xx) for scalatest's users. May be it will help some of you:

1. isolate the expectation phase into an helper method.
```
package org.scalamock

import org.scalamock.context.MockContext

object MockHelper {
    def verify(ctx: MockContext) {
        ctx.callLog foreach ctx.expectationContext.verify _
        if (!ctx.expectationContext.isSatisfied)
          ctx.reportUnsatisfiedExpectation(ctx.callLog, ctx.expectationContext)
    }
}
```
2. call the method into scalatest eventually, with [eventually](http://doc.scalatest.org/2.2.4/index.html#org.scalatest.concurrent.Eventually), you can define the total time to wait, interval between test :
```
class TestSupport(system: ActorSystem) extends TestKit(system) with ImplicitSender with FlatSpecLike with ScalaFutures with MockFactory with OneInstancePerTest {

  "SUT" should "blalabla" in {
    //...
    eventually { MockHelper.verify(this) }
  }
}
```

**Comment by michaelahlers** [comment] 2016-03-11 23:44
Stumbled upon this frustrating limitation tonight. It seems this would be easily resolved by allowing a call to `returns` without expecting the function ever gets called. (Bearing in mind retains the usefulness of mocks in that it saves on verbosity.)

**Comment by JavierCane** [comment] 2016-11-03 08:19
Hi @fommil,

We're having the very same issue you described in https://github.com/paulbutcher/ScalaMock/issues/101#issuecomment-88502097 (a `trait` mock being injected to an actor with an mocked behaviour like the following one, and never being called):

Trait implementation mocked behaviour:
```scala
    (context.someCoolClient.someFunction _)
      .expects(some, cool, parameters)
      .once()
      .returns(Future(true))
```

As you said in your first post, if we add debug traces, it always match the expectations and passes. We're also mixing the `OneInstancePerTest` trait in our tests, and calling the `verify` function shared by @davidB at https://github.com/paulbutcher/ScalaMock/issues/101#issuecomment-118839824 forcing a 6 seconds timeout without any success: 

```scala
  def eventuallyMakeMocksAssertions(ctx: MockContext): Unit = {
    val timeout = Timeout(6.seconds)

    eventually(timeout)(verify(ctx))
  }

  def verify(ctx: MockContext) {
    ctx.callLog.foreach(call => ctx.expectationContext.verify(call))
    if (!ctx.expectationContext.isSatisfied) {
      ctx.reportUnsatisfiedExpectation(ctx.callLog, ctx.expectationContext)
    }
  }
```

What kind of akka timing issue have you had? Thx!

The errors are like the following one:

```scala
sbt.ForkMain$ForkError: org.scalatest.exceptions.TestFailedException: Unsatisfied expectation:

Expected:
inAnyOrder {
  <mock-2> SomeCoolClient.someFunction(*, SomeId(c97a3bb2-ffef-41cb-ac8c-dcd93868f433), *) once (never called - UNSATISFIED)
}

Actual:

    at org.scalamock.scalatest.AbstractMockFactory$class.newExpectationException(AbstractMockFactory.scala:51)
    at com.company.coolapp.test.infrastructure.IntegrationSpec.newExpectationException(IntegrationSpec.scala:37)
    at com.company.coolapp.test.infrastructure.IntegrationSpec.newExpectationException(IntegrationSpec.scala:37)
    at org.scalamock.context.MockContext$class.reportUnsatisfiedExpectation(MockContext.scala:45)
    at com.company.coolapp.test.infrastructure.IntegrationSpec.reportUnsatisfiedExpectation(IntegrationSpec.scala:37)
    at org.scalamock.MockFactoryBase$class.verifyExpectations(MockFactoryBase.scala:98)
    at org.scalamock.MockFactoryBase$class.withExpectations(MockFactoryBase.scala:52)
    at com.company.coolapp.test.infrastructure.IntegrationSpec.withExpectations(IntegrationSpec.scala:37)
    at org.scalamock.scalatest.AbstractMockFactory$class.withFixture(AbstractMockFactory.scala:34)
    at com.company.coolapp.test.infrastructure.IntegrationSpec.withFixture(IntegrationSpec.scala:37)
    at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
    at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
    at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
    at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
    at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:962)
    at com.company.coolapp.test.acceptance.protocol.commands.SendMessageCommandBlockedSpec.org$scalatest$OneInstancePerTest$$super$runTest(SendMessageCommandBlockedSpec.scala:19)
    at org.scalatest.OneInstancePerTest$class.runTest(OneInstancePerTest.scala:129)
    at com.company.coolapp.test.acceptance.protocol.commands.SendMessageCommandBlockedSpec.runTest(SendMessageCommandBlockedSpec.scala:19)
    at org.scalatest.OneInstancePerTest$class.runTests(OneInstancePerTest.scala:177)
    at com.company.coolapp.test.acceptance.protocol.commands.SendMessageCommandBlockedSpec.runTests(SendMessageCommandBlockedSpec.scala:19)
    at org.scalatest.Suite$class.run(Suite.scala:1424)
    at com.company.coolapp.test.infrastructure.IntegrationSpec.org$scalatest$WordSpecLike$$super$run(IntegrationSpec.scala:37)
    at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
    at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
    at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
    at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1067)
    at com.company.coolapp.test.infrastructure.IntegrationSpec.org$scalatest$BeforeAndAfterAll$$super$run(IntegrationSpec.scala:37)
    at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:257)
    at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:256)
    at com.company.coolapp.test.infrastructure.IntegrationSpec.run(IntegrationSpec.scala:37)
    at org.scalatest.OneInstancePerTest$class.runTest(OneInstancePerTest.scala:126)
    at com.company.coolapp.test.acceptance.protocol.commands.SendMessageCommandBlockedSpec.runTest(SendMessageCommandBlockedSpec.scala:19)
    at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
    at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
    at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
    at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
    at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
    at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
    at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
    at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
    at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
    at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1021)
    at com.company.coolapp.test.acceptance.protocol.commands.SendMessageCommandBlockedSpec.org$scalatest$OneInstancePerTest$$super$runTests(SendMessageCommandBlockedSpec.scala:19)
    at org.scalatest.OneInstancePerTest$class.runTests(OneInstancePerTest.scala:184)
    at com.company.coolapp.test.acceptance.protocol.commands.SendMessageCommandBlockedSpec.runTests(SendMessageCommandBlockedSpec.scala:19)
    at org.scalatest.Suite$class.run(Suite.scala:1424)
    at com.company.coolapp.test.infrastructure.IntegrationSpec.org$scalatest$WordSpecLike$$super$run(IntegrationSpec.scala:37)
    at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
    at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
    at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
    at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1067)
    at com.company.coolapp.test.infrastructure.IntegrationSpec.org$scalatest$BeforeAndAfterAll$$super$run(IntegrationSpec.scala:37)
    at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:257)
    at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:256)
    at com.company.coolapp.test.infrastructure.IntegrationSpec.run(IntegrationSpec.scala:37)
    at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:466)
    at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:677)
    at sbt.ForkMain$Run$2.call(ForkMain.java:296)
    at sbt.ForkMain$Run$2.call(ForkMain.java:286)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by JavierCane** [comment] 2016-11-04 09:23
We've found out the race condition. Just in case it helps out someone:

Until the refactor that provoke this behaviour, we were subscribing the actors to the event bus from the outside, and then, executing the test and verifying the mocks expectations.

The refactor consist in injecting the event bus to the actors, and moving the subscription logic to the actors `preStart` method (considering that it was their responsibility).

The fact is that we're executing the test just after instantiating the actors, so it seems that when the test run in TeamCity (& without any `println`), they run too fast and the actors does not has enough time to subscribe to the event bus. So if the call to the mocked trait depends on an event arriving previously to the actor, it will not be called.

The problem with all of that was the difficulty of debugging it (since the test run slower locally, it didn't happen, and if we add some debug traces in the CI server, we were slowing the execution just enough to not being able to reproduce the issue).

We've solved it just adding a sad `Thread.sleep(200)` between the actors initialization, and the test execution. :/

**Comment by fommil** [comment] 2016-11-04 10:09
yeah, actors do tend to provoke those kinds of workarounds...

**Comment by barkhorn** [comment] 2017-01-22 14:38
It seems this is not a bug in ScalaMock afterall, going by https://github.com/paulbutcher/ScalaMock/issues/101#issuecomment-88861763 
Closing this for now, unless someone still feels there is a synchronisation bug in the library, and can point at some (more or less) reproducable example.

**Closed by barkhorn** 2017-01-22 14:38 UTC
Labels: bug, still-valid?

**Comment by ngochai94** [comment] 2017-02-20 08:11
Do we have any different way to check the mock with async operation other than [davidB's workaround](https://github.com/paulbutcher/ScalaMock/issues/101#issuecomment-118839824)?
But for his code, there's a potential issue with checking the same `log` again, I think a `clonedContext` should be created to not affect the `context`
`
object MockHelper {
  def verify(context: MockContext): Unit = {
    val clonedContext = context
    context.callLog foreach { x: Call =>
      clonedContext.expectationContext.verify(x)
      ()
    }
    if (!clonedContext.expectationContext.isSatisfied) {
      context.reportUnsatisfiedExpectation (context.callLog, context.expectationContext)
    }
  }
}
`

**Comment by barkhorn** [comment] 2017-02-20 09:37
@ngochai94  I don't use Async tests myself much, but maybe the AsyncMockFactory can help your use-case?
It's wired against ScalaTest's AsyncTestSuite:

https://github.com/paulbutcher/ScalaMock/blob/master/frameworks/scalatest/shared/src/main/scala/org/scalamock/scalatest/AsyncMockFactory.scala

**Comment by arbitrary-dev** [comment] 2017-11-17 13:09
There is a problem with [solution provided by](#issuecomment-118839824) @davidB, it doesn't check for `ctx.callLog` containing only verified calls, here is fixed version:
```
object MockHelper {
  def verify(ctx: MockContext): Unit = {
    var valid = true
    ctx.callLog foreach { c => valid &= ctx.expectationContext.verify(c) }
    if (!(valid && ctx.expectationContext.isSatisfied))
      ctx.reportUnsatisfiedExpectation(ctx.callLog, ctx.expectationContext)
  }
}
```
