### ISSUE TITLE
Mock slick.jdbc.JdbcBackend.Session

### ISSUE THREAD

**Issue by maciejbak85** [paulbutcher/ScalaMock#266] opened 2019-06-20 07:02 UTC
*If you want to discuss a new feature, please ignore/clear this form.*

### ScalaMock Version (e.g. 3.5.0)
4.1.0

### Scala Version (e.g. 2.12)
2.12.8

### Runtime (JVM or JS)
JVM

### Please describe the expected behavior of the issue
 `val sessionMock = mock[slick.jdbc.JdbcBackend.Session] `
would mock perfectly

### Please provide a description of what actually happens
ome of my methods takes session an an implicit param. Which wont't be used inside, because it is passed in code to repo's where queries are done and where it is needed. Of course I mock repos, so I dont need session, but while mocking it I get an error:

`val sessionMock = mock[slick.jdbc.JdbcBackend.Session]`

```
Error:(28, 25) object creation impossible, since:
it has 2 unimplemented members.
/** As seen from <$anon: slick.jdbc.JdbcBackend.Session>, the missing signatures are as follows.
 *  For convenience, these are usable as stub implementations.
 */
  private[package slick] def endInTransaction(f: => Unit): Unit = ???
  private[package slick] def startInTransaction: Unit = ???
  val sessionMock = mock[slick.jdbc.JdbcBackend.Session]
```
It works for example with mockito:

`org.mockito.Mockito.mock(classOf[Session])`
but I can not make it working with scalamock..

### Reproducible Test Case

```scala
test("my failing test") {
implicit val sessionMock = mock[slick.jdbc.JdbcBackend.Session]
runMethodWhichTakesSessionAsImplicitParamButDontUseIt()
}
```

**Comment by barkhorn** [comment] 2019-06-20 15:53
First, one important piece of info: All mocks are subclasses of the type to mock.
The error message is quite clear here I think. 
There are package private methods defined as abstract members, which are expected to be implemented by the subclasses (in this case the mock).
however, as they are package private, they are elided during mock creation. This is deliberate.
You would have to create a subclass yourself with some concrete overrides, or abstract - but public - overrides, and then mock that class instead.
This subclass should also live in the `slick` package.

Closing this, as not a bug.
If you need further help with mocking this particular class, please post on StackOverflow.

**Closed by barkhorn** 2019-06-20 15:53 UTC
