### ISSUE TITLE
Can't mock overloaded methods

### ISSUE THREAD

**Issue by BrianLondon** [paulbutcher/ScalaMock#189] opened 2017-06-02 19:48 UTC
Consider the following simple class with overloaded method names and attached test.

```scala
case class Foo(number: Int, string: String) {
  def add(x: Int) = Foo(x + number, string)
  def add(s: String) = Foo(number, string + s)
}

class FooSpec extends FlatSpec with MockFactory {
  "Foo" should "call add(x: Int)" in {
    val foo = mock[Foo]

    (foo.add _).expects(3).returns(Foo(7, "foo"))

    foo.add(3) shouldEqual Foo(7, "foo")
  }
}
```

The above code will not compile with an *ambiguous reference to overloaded definition* error since the eta expansion doesn't know which `add` method I'm trying to expand.  Ordinarily one would get the function by assigning the expansion to an explicitly typed value such as:

```scala
    val fooAdd: Int => Foo = foo.add _
    fooAdd.expects(3).returns(Foo(7, "foo"))
```

However that results in a compile error *Unrecognised structure: Ident(TermName("fooAdd")).Please open a ticket at https://github.com/paulbutcher/ScalaMock/issues* in 3.5.0, or even worse *please declare 'fooAdd' as MockFunctionx or StubFunctionx (e.g val fooAdd: MockFunction1[X, R] = ... if it has 1 parameter)* in 3.6.0.

Trying to make both steps explicit as below also doesn't work.

```scala
    val fooAdd: Int => Foo = foo.add
    val fooAddMock: MockFunction1[Int, Foo] = fooAdd
    fooAdd.expects(3).returns(Foo(7, "foo"))
```

**Comment by BrianLondon** [comment] 2017-06-02 19:57
For completeness I want to add that the following also doesn't work:

```scala
(foo.add(_: Int)).where(3).returns(Foo(7, "foo"))
```

*value where is not a member of Int => Foo*

**Comment by barkhorn** [comment] 2017-06-02 21:28
can't reproduce this.

The code snippet in your first example is invalid, as the documentation explains.

`(foo.add(_: Int)).expects(3).returns(Foo(7, "foo"))` works just fine with 3.6.0

**Comment by BrianLondon** [comment] 2017-06-05 20:18
Interesting, now I can't get that line to fail either. There might have been something else funny going on in the file I was playing with.

**Comment by barkhorn** [comment] 2017-06-06 06:58
Thanks @BrianLondon . Happy if i close this then?

**Comment by BrianLondon** [comment] 2017-06-06 15:09
Yeah, that's fine. Sorry for the trouble.

**Comment by barkhorn** [comment] 2017-06-07 07:28
no problem, thanks :)

**Closed by barkhorn** 2017-06-07 07:28 UTC
