### ISSUE TITLE
ScalaMock using wrong property under Scala.js

### ISSUE THREAD

**Issue by ochrons** [paulbutcher/ScalaMock#185] opened 2017-04-24 06:30 UTC
### Runtime Scala.js
Works fine under JVM but fails on Scala.js

### Please provide a description of what actually happens
```
[info]   java.lang.IllegalArgumentException: Property 'mock$createChannel$0$2' is not defined in 'suzaku.ui.UIManagerSpec$TestUIManager$$anon$1@18'. Available properties: protocol$1,id$1,globalId$1,parent$1,handler$1,context$1,handlerFunc$1,subChannels$1,channelIdx$1,router$1,bitmap$0$1,$$outer$f,mock$special$mockName$3,mock$createChannel$0$3,mock$send$0$3,mock$close$0$3,mock$receiveDrop$0$3,mock$receive$0$3,mock$closeChannel$0$3
```

### Reproducible Test Case
https://github.com/suzaku-io/suzaku/blob/298e2a30754ebefe6a6ea27518ba7c0d5be827d5/core/shared/src/test/scala/suzaku/ui/UIManagerSpec.scala#L76-L88

in project https://github.com/suzaku-io/suzaku

Run `coreJS/test` to invoke the wrong behavior.

Quote from @sjrd

> It looks like a binary-incompatibility of sorts, triggered by a change in the number of superclasses of `suzaku.ui.UIManagerSpec$TestUIManager$$anon$1`. That would changed the mangling of `mock$createChannel$0$2` (with 2 superclasses) to `...$3` (with 3 superclasses).
In principle, since those fields are private, this cannot show up in user space, as private fields can only be accessed from the same compilation unit, and a compilation unit is always recompiled entirely.

**Comment by barkhorn** [comment] 2017-04-24 07:15
ScalaMock is still built against some older versions (2.11.8 with js 0.6.14)
Could this be related to 2.11.11 and the version of Scala.JS you are using? (0.6.15).
Are you able to check with the older versions?

**Comment by ochrons** [comment] 2017-04-30 20:38
I tested with 2.11.8 and Scala.js 0.6.14 and the result was the same.

**Comment by barkhorn** [comment] 2017-05-01 09:06
Would it be possible to get a smaller code snippet that exposes the problem, but without all the dependencies?
I can't resolve at least one of them:

`[warn] 	:: io.suzaku#arteria-core_sjs0.6_2.12;0.1.0-SNAPSHOT: not found`

Another suggestion i would have, based on the compilation unit/superclasses comment above, would be to put these classes inside an object, or top-level:

```
  class MockUIHandler extends MessageChannelHandler[UIProtocol.type]

  class MockUIChannel extends MessageChannel(UIProtocol)(0, 0, null, new MockUIHandler, null) {}

  class MockWidgetHandler extends MessageChannelHandler[TestProtocol.type]

  class MockWidgetChannel extends MessageChannel(TestProtocol)(0, 0, null, new MockWidgetHandler, ()) {}
```

Currently, they are inner classes and tied to an instance of `TestUIManager`, and others.

**Comment by ochrons** [comment] 2017-05-01 16:41
I tried having those classes on top-level and within an object, but no change in results.

Arteria is the library I'm mocking here and I was not able to replicate the issue within that project alone even by copying the same code over to its test suite. It worked fine within that project.

It seems to generate the correct code in that case:
```js
var fld$macro$18 = $g.Object.getOwnPropertyDescriptor(this.channel$1, "mock$createChannel$0$3");
```
whereas in Suzaku it generates:
```js
var fld$macro$2 = $g.Object.getOwnPropertyDescriptor(this.uiChannel$1, "mock$createChannel$0$2");
```

The SNAPSHOT should be available in the Sonatype snapshots repo, and the build.sbt should have `resolvers += "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"` to include it.

You can also `publishLocal` the [Arteria](https://github.com/suzaku-io/arteria/) library to get it working.

**Comment by barkhorn** [comment] 2017-05-06 16:53
getting a different error now.
```
[trace] Stack trace suppressed: run last coreJS/test:loadedTestFrameworks for the full output.
[error] (coreJS/test:loadedTestFrameworks) java.io.IOException: Cannot run program "node": error=2, No such file or directory
```

I am not sure how we can progress looking into this potential bug without a stable example that I can test with.
Your project is fairly sizable and will slow matters down :/

**Comment by ochrons** [comment] 2017-05-06 17:26
Right, you need to install NodeJS on your computer as all Scala.js tests are run using Node. I can try to isolate it into a single minimized test case in the Suzaku project, to make it easier to debug.

**Comment by barkhorn** [comment] 2017-05-06 17:30
please do, if you can just put it on some branch and point me at that.
any particular version of node.js needed?

**Comment by ochrons** [comment] 2017-05-06 17:32
Anything above Node v6 should work fine.

**Comment by ochrons** [comment] 2017-05-10 17:17
I simplified the test case as much as possible and it can be found in branch https://github.com/suzaku-io/suzaku/tree/scalamock185

Running `coreJS/test` runs just this single test that exposes the problem.

**Comment by barkhorn** [comment] 2017-05-12 20:22
Thanks for that branch, I think I understand this now:

By setting up the mock inside the TestUIManager, it seems to have changed the number of superclasses somehow.
This is not something ScalaMock has influence over as the ScalaMock macros simply create anonymous subclasses - as you can see from the reference to `suzaku.ui.UIManagerSpec$TestUIManager$$anon$1@b` in the exception.

So i factored the mock out into a Fixture (and added a foo() function to have a test assertion on it), and iy all looks good.
I've also added your test doubles back into the suite to check that they don't have to be top level classes.

Closing this as not a bug, unless you have objections?

Here is my refactored UIManagerSpec:
```
package suzaku.ui

import arteria.core.{Message, MessageChannel, MessageChannelHandler, Protocol}
import suzaku.{TestLogger, UnitSpec}
import boopickle.Default._
import org.scalamock.scalatest.MockFactory

class UIManagerSpec extends UnitSpec with MockFactory {
  object TestProtocol extends Protocol {
    override type ChannelContext = Unit

    sealed trait TestMessage extends Message

    private val tmPickler = compositePickler[TestMessage]

    implicit val (messagePickler, witnessMsg) = defineProtocol(tmPickler)

    override val contextPickler = implicitly[Pickler[Unit]]
  }

  class MockUIHandler extends MessageChannelHandler[UIProtocol.type]

  class MockUIChannel extends MessageChannel(UIProtocol)(0, 0, null, new MockUIHandler, null)

  class TestUIManager(val uic: MessageChannel[UIProtocol.type]) extends UIManager(TestLogger, _ => (), () => ()) {
    def foo(): Unit = uic.close()
  }

  trait MockFixture {
    val uiChannel = mock[MockUIChannel]

    (uiChannel
      .createChannel(_: TestProtocol.type)(_: MessageChannelHandler[TestProtocol.type],
        _: TestProtocol.type#ChannelContext,
        _: Any)(_: Pickler[Any]))
      .expects(*, *, *, *, *).anyNumberOfTimes()

    uiChannel.close _ expects() once()
  }

  "View manager child update" should {
    "update nothing" in new MockFixture {
      val vm = new TestUIManager(uiChannel)
      vm.uic shouldNot be(null)
      vm.foo()
    }
  }
}
```

```
> coreJS/test
[info] Compiling 1 Scala source to /home/phil/src/oss/suzaku/core/js/target/scala-2.12/test-classes...
[info] Fast optimizing /home/phil/src/oss/suzaku/core/js/target/scala-2.12/suzaku-core-test-fastopt.js
[info] UIManagerSpec:
[info] View manager child update
[info] - should update nothing
[info] Run completed in 339 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 6 s, completed 12-May-2017 21:17:25
```

**Closed by barkhorn** 2017-05-12 20:22 UTC

**Comment by ochrons** [comment] 2017-05-14 07:29
Thanks for figuring out a workaround! Perhaps @sjrd might have some idea why this happens only on Scala.js?

**Comment by sjrd** [comment] 2017-06-02 11:06
My analysis [here](https://github.com/scala-js/scala-js/issues/2952#issuecomment-305757119) suggests that is is actually a bug on ScalaMock's side.
