### ISSUE TITLE
mock Generic Class

### ISSUE THREAD

**Issue by artvovc** [paulbutcher/ScalaMock#201] opened 2017-09-13 14:35 UTC
Hi! i`m new in using ScalaMock. Need to create an mock or stub for an Generic Class **Repository**. 
```cc
class FirstUT extends WordSpec with MustMatchers with MockFactory {
  "Some class" should {
    "do" in {
      val cl = stub[Repository[Wrap]]
      (cl.save _).when(*).returns("88585")
      val serviceOne = new ServiceOne(cl)
      serviceOne.save("88585") mustBe "8858588585"
    }
  }
}
```

```cc
Error:(7, 20) type mismatch;
 found   : A
 required: Wrap
      val cl = stub[Repository[Wrap]]
```
```cc
class ServiceOne(val repo:Repository[Wrap]){
  def save(str:String): String = {
    println("ServiceOne Save")
    repo.save(str) + str
  }
}
class Repository[A](val entity: A) {
  def save(str:String) = {
    println("saving")
    str + str
  }
}
case class Wrap()
```
If remove Repository constructor no errors occurs, but it is not answer.

**Comment by barkhorn** [comment] 2017-09-14 07:04
Seems to be a duplicate of #170 
I would appreciate if you use the form next time to fill in the which version of scalamock you used etc.

**Closed by barkhorn** 2017-09-14 07:04 UTC
