### ISSUE TITLE
Mocking case classes and classes without default constructor

### ISSUE THREAD

**Issue by spontagent** [paulbutcher/ScalaMock#56] opened 2014-01-15 10:08 UTC
How would I mock case classes?

**Comment by gavares** [comment] 2015-03-04 17:04
This strategy works but requires quite a bit of boilerplate in a project that has a lot of case classes. Being able to `mock[MyCaseClass]` would be very useful.

**Comment by eamonnfaherty-productmadness** [comment] 2015-06-19 13:24
:+1:

**Comment by danmbyrd** [comment] 2015-06-24 00:30
:+1: This would be great if we could avoid the boiler plate.

**Comment by jeroenvlek** [comment] 2015-07-22 13:08
:thumbsup:

**Comment by michaelahlers** [comment] 2015-07-27 16:45
:+1:

**Comment by tricker** [comment] 2015-09-02 15:30
:+1:

**Comment by gabadi** [comment] 2015-09-17 15:25
+1

**Comment by szabba** [comment] 2015-09-29 15:24
:+1:

**Comment by nolanofra** [comment] 2015-10-06 14:01
:+1:

**Comment by psttf** [comment] 2015-10-18 21:14
:+1:

**Comment by fajarmf** [comment] 2015-10-19 09:11
:+1:

**Comment by autodidacticon** [comment] 2015-11-03 22:03
:+1:

**Comment by eyalroth** [comment] 2015-12-08 15:26
:+1:

**Comment by gabadi** [comment] 2015-12-23 01:15
+1

**Comment by nolanofra** [comment] 2015-12-30 08:39
:+1:

**Comment by lhohan** [comment] 2016-02-09 14:43
:+1:

**Comment by snaik** [comment] 2016-02-21 00:17
:+1:

**Comment by bkowalik** [comment] 2016-03-18 19:20
I have made PR. Please make review.

**Comment by eviatharbl** [comment] 2016-03-30 19:17
+1

**Comment by atanana** [comment] 2016-04-30 12:02
+1

**Comment by Jaca777** [comment] 2016-05-05 13:39
+1
I'm totally unable to use it with akka testkit because of it.

**Comment by JosephSe** [comment] 2016-07-28 13:56
+1

**Comment by greenhost87** [comment] 2016-07-29 08:23
+1

**Comment by smrnv** [comment] 2016-07-29 08:24
+1

**Comment by burungbangkai** [comment] 2016-07-29 11:38
+1

**Comment by akhil** [comment] 2016-08-26 18:57
+1

**Comment by xavier-fernandez** [comment] 2016-09-15 04:35
+1

**Comment by supramo** [comment] 2016-09-22 21:09
+1

**Comment by barkhorn** [comment] 2017-01-07 16:55
just merged some code into master to support constructors with parameters

**Closed by barkhorn** 2017-01-07 16:55 UTC
Labels: confirmed, feature

**Comment by ddpaimon** [comment] 2017-06-26 10:03
:+1:

**Comment by bbarker** [comment] 2017-10-27 00:15
I still (in 3.6.0) seem to experience an NPE on mocking a class `TableLactationCurves` that looks like the following:

```scala
class TableLactationCurves(stream: InputStream) extends DataSetXml(stream) with LactationCurves {
```

The problem is in the `DataSetXml` constructor:

```scala
class DataSetXml(stream: InputStream) {
  protected var dataTypes: mutable.Map[String, DataType] = mutable.Map()
  protected var data: Array[Array[Any]] = null
  private var description: String = null

  try {
    val is = new InputSource()
    is.setCharacterStream(new StringReader(Utils.readStringFromInputStream(stream)))
    loadData(null, is)
  } catch {
    case ex: Exception =>
      throw new RuntimeException(ex)
  }
```

Of course, i could fix this by not throwing a `RuntimeException`, I suppose, but that would change application behavior.
