### ISSUE TITLE
Cannot mock a trait with type parameters

### ISSUE THREAD

**Issue by WenjunHuang** [paulbutcher/ScalaMock#193] opened 2017-08-08 08:16 UTC
*If you want to discuss a new feature, please ignore/clear this form.*

### Runtime (JVM or JS)
JVM

### Please provide a description of what actually happens
can not compile due to error "value when is not a member of (String, FooEntityFO, akka.actor.ActorRef) => Unit
    (mock.persistEntity(_:String,_:FooEntityFO, _:ActorRef)).when("abc",fo,*)"

Here are my codes.

```scala
trait FieldsObject[FO] {
  def assignId(id:String):FO
  def id:String
}
trait Repository[FO <: FieldsObject[FO]] {
  def loadEntity(id: String): Future[ServiceResult[FO]]

  def loadEntity(id: String, replyTo: ActorRef):Unit

  def persistEntity(id:String, fo: FO): Future[ServiceResult[FO]]

  def persistEntity(id:String, fo: FO, replyTo: ActorRef):Unit

  def deleteEntity(id: String): Future[ServiceResult[FO]]

  def deleteEntity(id: String, replyTo: ActorRef):Unit
}
```
```scala
case class FooEntityFO(override val id: String) extends FieldsObject[FooEntityFO] {
  override def assignId(id: String) = copy(id = id)
}

class FooTestSpec extends FunSuite with Matchers with MockFactory{
  test("some test") {
    val mock = stub[Repository[FooEntityFO]]
    val fo = FooEntityFO("abc")
    (mock.persistEntity(_:String,_:FooEntityFO, _:ActorRef)).when("abc",fo,*) // compiler error here
  }
}
```

**Comment by barkhorn** [comment] 2017-08-08 16:52
minimal failing example:

```scala
class FooTest extends FunSuite with Matchers with MockFactory {
  trait Foo[T] {
    def foo(x: T, i: Int): Unit
    def foo(x: T): Unit
  }

  test("foo") {
    val mock = stub[Foo[Int]]
    (mock.foo(_: Int, _: Int)).when(*, *)
  }
}
```

looks like this is a problem with the combination of trait with type parameter + overloading.

Output I am getting for this:
```
Information:(15, 14) Unable to resolve overloaded method foo
    (mock.foo(_: Int, _: Int)).when(*, *)
Error:(15, 32) value when is not a member of (Int, Int) => Unit
    (mock.foo(_: Int, _: Int)).when(*, *)
```

The implicit conversion for when is using `MockImpl.toStubFunction2`, which in turn uses `MockFunctionFinder`.
The first message in the output is ScalaMock complaining that it cannot resolve the overloaded method, which is the root cause of the problem

**Comment by barkhorn** [comment] 2017-08-08 18:04
specifically `MockFunctionFinder.resolveOverloaded.sameTypes` does not succeed in dealiasing "these" and no match is found

**Comment by barkhorn** [comment] 2017-08-08 18:14
This looks like a duplicate of #93. Thanks for reporting this. I will post updates on the existing ticket but feel this might be pretty hard to fix given Pawl and Paul both had a look already.

**Closed by barkhorn** 2017-08-08 18:14 UTC
Labels: in progress
